import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve, relative } from 'node:path'
import type { ChildProcess } from 'node:child_process'
import type { BackendAdapter, LaunchHandle, LaunchOptions, EmitOptions } from './types.ts'
import type { SiteIR, Collection, Field, FieldType, CollectionFormat } from '../ir/types.ts'
import { hasCommand, openInBrowser, spawn } from './util.ts'

const LUME_CMS_IMPORT = 'https://cdn.jsdelivr.net/gh/lumeland/cms@v0.15.5/mod.ts'
const LUME_SERVE_PORT = 8000

export const lume: BackendAdapter = {
  name: 'lume',

  async isAvailable() {
    return await hasCommand('deno')
  },

  async emitConfig(ir: SiteIR, outDir: string, opts: EmitOptions = {}): Promise<void> {
    const lumeDir = join(outDir, 'lume')
    const cmsPath = join(lumeDir, '_cms.ts')
    if (!opts.force && existsSync(cmsPath)) {
      throw new Error(`${cmsPath} exists; pass --force to overwrite.`)
    }
    mkdirSync(lumeDir, { recursive: true })

    const siteRootAbs = resolve(ir.siteRoot)
    const fromLumeDirToSite = toForwardSlashes(relative(lumeDir, siteRootAbs)) || '.'

    const lines: string[] = []
    lines.push(`// Generated by SimpleSiteEdit. Do not edit by hand.`)
    lines.push(`import lumeCMS from "${LUME_CMS_IMPORT}";`)
    lines.push(``)
    lines.push(`const cms = lumeCMS();`)
    lines.push(``)
    lines.push(`cms.storage("fs", ${JSON.stringify(fromLumeDirToSite)});`)
    lines.push(``)

    for (const c of ir.collections) {
      const globPattern = collectionGlob(c)
      // Lume's `body → content` convention applies only to markdown-family files,
      // where the storage layer extracts the markdown body into `entry.content`.
      // JSON-backed collections (js-literals) keep whatever key the source uses.
      const usesMdBodyConvention = c.format === 'markdown' || c.format === 'mdx'
      const fields = c.fields
        .map((f) => {
          const name = usesMdBodyConvention && f.type === 'markdown' && f.name === 'body'
            ? 'content'
            : f.name
          return `  ${JSON.stringify(`${name}: ${fieldTypeToLumeWidget(f.type)}`)}`
        })
        .join(',\n')
      lines.push(
        `cms.collection(\n` +
        `  ${JSON.stringify(c.name)},\n` +
        `  ${JSON.stringify(`fs:${globPattern}`)},\n` +
        `  [\n${fields}\n  ]\n` +
        `);`,
      )
      lines.push(``)
    }

    lines.push(`export default cms;`)
    lines.push(``)

    writeFileSync(cmsPath, lines.join('\n'))
  },

  async launch(ir: SiteIR, outDir: string, opts: LaunchOptions = {}): Promise<LaunchHandle> {
    const lumeDir = resolve(outDir, 'lume')
    const cmsPath = join(lumeDir, '_cms.ts')
    if (!existsSync(cmsPath)) {
      throw new Error(`emitConfig must be called before launch (missing ${cmsPath})`)
    }
    if (!(await hasCommand('deno'))) {
      throw new Error(
        'deno is not installed.\n' +
        '  Install it from https://deno.com/\n' +
        '  Then re-run SimpleSiteEdit.',
      )
    }

    const proc = spawnDeno(cmsPath, lumeDir)
    const url = `http://localhost:${LUME_SERVE_PORT}/`

    if (!opts.noOpen) openInBrowser(url)

    return {
      url,
      stop: async () => {
        proc.kill()
      },
    }
  },
}

function collectionGlob(c: Collection): string {
  switch (c.format) {
    case 'markdown': return `${c.folder}/*.md`
    case 'mdx':      return `${c.folder}/*.mdx`
    case 'json':     return `${c.folder}/*.json`
    case 'yaml':     return `${c.folder}/*.yml`
  }
}

function fieldTypeToLumeWidget(t: FieldType): string {
  switch (t) {
    case 'string':   return 'text'
    case 'datetime': return 'datetime'
    case 'list':     return 'list'
    case 'boolean':  return 'checkbox'
    case 'markdown': return 'markdown'
    case 'image':    return 'file'
    case 'unknown':  return 'text'
  }
}

function toForwardSlashes(p: string): string {
  return p.replace(/\\/g, '/')
}

function spawnDeno(cmsPath: string, cwd: string): ChildProcess {
  return spawn(
    'deno',
    ['serve', '--allow-all', '--node-modules-dir=auto', `--port=${LUME_SERVE_PORT}`, cmsPath],
    { cwd, stdio: 'inherit' },
  )
}
